language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: l3//5uB4OZBwoBN32yDEtZ4fBseC4gvfRnkseITgSN4jJS4O3F2YUqnFhKEh9Q7+fkLbWhtq33wojn/QB/r/QLEI0CWj+QGSjfAvSc8i8MOSauWHY9UZ2yNAlgYkPT6ehePmNXpCMBGewOPyvNnxfmAY30GxzHpdm3anlT9IoIDNtJVEzI49zuMrIIVDAWPlUjn1La2X4K+uIsty9nn1rniEWUs56snTaj0oYw/F2KjogqYIkf87PUA5XG6H+K4kkwXj/sZDs2WBvUNolj7b0pYC7zbpF28tbJuttPsba6gN/V8IJmsprAtTf5igHXH+96Am92vrqjFtzG+bA2ISn1Yrs9xpdb3XFW2oBq9+lxDY+Eb3XLNXfOHwUmIoZLLJxMtiJXmTWOHC5aDg4woR5MZLsxKe23aPwEnfAOozVus7eVoEQ833va50jXPIDOiT7tNROLxUgC/+Wih145RxhAiQZo3Q2wgOPo/J0kmH0G153fK22bFWLbGMecha/LEjWXxu/Q4RAduneTf+w0wBQNaNF9RyE9NDf+nY7csgmkflPio4pSzcuKQirqKw1hQfKJuHIG43kTS6VDBVKWe8kLzRefHlq/3T2NsCUfLtY68CYlgHqcCa5r+teGWnfAwXAG15XsBTZUhEn5uvu/tZ6zY/NSLcyyKnCyvObmGySNM=
  app: 'radiant-mesa-60191'